#!/usr/bin/env node

/**
 * GitHub Labels Creator
 * Miyabiフレームワークのラベル体系を作成
 */

import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

const labels = [
  // Type labels
  { name: 'bug', color: 'd73a4a', description: 'Something isn\'t working' },
  { name: 'feature', color: '0075ca', description: 'New feature or request' },
  { name: 'enhancement', color: 'a2eeef', description: 'New feature or request' },
  { name: 'documentation', color: '0052cc', description: 'Improvements or additions to documentation' },
  { name: 'refactor', color: 'fbca04', description: 'Code refactoring' },
  { name: 'test', color: 'bfd4f2', description: 'Testing related' },
  { name: 'chore', color: 'fef2c0', description: 'Maintenance tasks' },
  
  // Priority labels
  { name: 'priority:critical', color: 'b60205', description: 'Critical priority' },
  { name: 'priority:high', color: 'd93f0b', description: 'High priority' },
  { name: 'priority:medium', color: 'fbca04', description: 'Medium priority' },
  { name: 'priority:low', color: 'c5def5', description: 'Low priority' },
  
  // Component labels
  { name: 'frontend', color: 'c2e0c6', description: 'Frontend related' },
  { name: 'backend', color: 'fef2c0', description: 'Backend related' },
  { name: 'database', color: '5319e7', description: 'Database related' },
  { name: 'api', color: 'fbca04', description: 'API related' },
  { name: 'security', color: 'ee0701', description: 'Security related' },
  { name: 'performance', color: '1d76db', description: 'Performance improvements' },
  { name: 'dx', color: '0e8a16', description: 'Developer experience' },
  
  // Complexity labels
  { name: 'complexity:small', color: '006b75', description: 'Small task (< 4 hours)' },
  { name: 'complexity:medium', color: 'fbca04', description: 'Medium task (1-2 days)' },
  { name: 'complexity:large', color: 'd93f0b', description: 'Large task (3-5 days)' },
  { name: 'complexity:xlarge', color: 'b60205', description: 'Extra large task (1+ week)' },
  
  // Miyabi Agent labels
  { name: '🤖agent-execute', color: '7057ff', description: 'Trigger Miyabi Agent execution' },
  { name: '🤖agent-generated', color: 'b4a7d6', description: 'Code generated by Agent' },
  { name: 'automated', color: '0052cc', description: 'Automated task' },
  { name: 'needs-review', color: 'fbca04', description: 'Needs code review' },
  { name: '🚨escalated', color: 'b60205', description: 'Escalated to human' },
  { name: '❌agent-failed', color: 'd73a4a', description: 'Agent execution failed' },
];

async function createLabels() {
  console.log('🏷️ Creating GitHub Labels...\n');

  for (const label of labels) {
    const command = `gh label create "${label.name}" --repo rikimaru63/cardshop-hp-miyabi --color "${label.color}" --description "${label.description}"`;
    
    try {
      console.log(`📌 Creating label: ${label.name}`);
      await execAsync(command);
      console.log(`   ✅ Created successfully!`);
    } catch (error) {
      if (error.message.includes('already exists')) {
        console.log(`   ⚠️ Label already exists, skipping...`);
      } else {
        console.error(`   ❌ Failed: ${error.message}`);
      }
    }
  }

  console.log('\n🎉 All labels processed!');
}

// メイン実行
createLabels().catch(console.error);